### ISSUE TITLE
WSU 125 Mark use documentation

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/brand.wsu.edu#9]
Would it be helpful to have some documentation (blog post?) on how the WSU 125 mark should be used in combination with the brand?

**Comment by natejacobson** [comment]
https://brand.wsu.edu/campaigns/

**Comment by natejacobson** [comment]
It would be a great idea to link to this page from the spine notes.

**Comment by jeremyfelt** [comment]
Ahh, I did a good job of reading, ha. :+1:

**Comment by natejacobson** [comment]
Well, in your defense, it wouldn't be obvious that one would find the 125th guides under Campaigns.
